### PR TITLE
Change iterator Item of I2c iter traits to use &u8

### PR DESCRIPTION
**Pull request by MabezDev**
Discussion issue: #154

### CODE REVIEW

**Comment by ryankurte** [comment]
hey thanks for the PR! this seems like a reasonable improvement, however, appears to be a breaking change, so will likely require some further discussion from @rust-embedded/hal

**Comment by MabezDev** [comment]
> Would it be possible to structure this as an addition instead of a change? i.e. add a new WriteIterRef and WriteIterRefRead (names possibly terrible) which operate in this way?

While it would be possible, I'd be interested in the use case of consuming the iterator on write. 

I would also like to propose changing name to `write_iter` not only because it better describes what it is, but because when implementing all these traits in a hal, having multiple methods named write causes ambiguity, if both traits were imported in a users program, the following would fail to compile.

```
use hal::blocking::i2c::{WriteIter, Write}

let buffer = [0xFF; 10];
i2c.write(0xAE, &buffer).unwrap(); // fails because &buffer implements into_iter and is &[u8]
```

I may be wrong here, but given the fact that these traits are behind the `unproven` feature, it would seem breaking changes are anticipated.

**Comment by jonas-schievink** [comment]
I'm not sure I understand the motivation for this. If you have an iterator that yields `&u8` you can just call `.copied()` on it to get one that yields `u8`.

**Comment by MabezDev** [comment]
I wasn't aware that was possible, in which case this PR pointless.

**Comment by jrmoulton** [comment]
How does using `.copied` fix the issue in #154?

I'm running into this very same problem when trying to write to an I2C EEPROM and needing to copy all of the data into a new buffer to have the address pre-pended. 

@eldruin I looked at the implementation in eeporm24x and it looks like that is still copying all of the data. 

Am I missing something?

**Comment by MabezDev** [comment]
@jrmoulton With the embedded-hal 1.0-rc's the iterative API has been removed, so for now the only way to do this is to have the address and data in a singular buffer.

**Pull request closed without merging**
