### PR TITLE
Separate Capture, Pwm and Qei traits into modules

### PR DESCRIPTION
**Pull request by eldruin**
The `lib.rs` file is already _very_ long. I propose separating these traits which are just at the end of the file into their own modules.
I have kept the modules private and reexported the traits and types to maintain the same interface.
However, for consistency with the other traits maybe it would be worth it to expose these new modules as well and not reexport the traits in `lib.rs`.
What do you think?

### CODE REVIEW

**Comment by ryankurte** [comment]
Seems like a good idea to me!
> However, for consistency with the other traits maybe it would be worth it to expose these new modules as well and not reexport the traits in lib.rs.

As part of the breaking changes happening in #192 I think we may as well fix this for consistency.

**Comment by eldruin** [comment]
@ryankurte done.

**Comment by eldruin** [comment]
@ryankurte sorry there were some errors in the documentation. They should be solved now.
On macOS `cross test --target=arm-unknown-linux-musleabihf` does not run the doc tests. Any idea why?

**Comment by eldruin** [comment]
Is anything preventing this being merged?

**Comment by ryankurte** [comment]
thanks for the reminder, looks good to me (though we're going to need to do a lot of changelog updating)

bors r+

**Pull request merged**
