### PR TITLE
Fix code formatting + check it on bors

### PR DESCRIPTION
**Pull request by eldruin**
This was missed in #246.

### CODE REVIEW

**Comment by eldruin** [comment]
bors try

**Review by therealprof — APPROVED** [review]
LGTM, thanks.

bors r+

**Comment by eldruin** [comment]
bors r=therealprof

**Comment by eldruin** [comment]
bors r=therealprof

**Comment by eldruin** [comment]
bors try

**Comment by eldruin** [comment]
bors try

**Comment by eldruin** [comment]
bors try

**Comment by eldruin** [comment]
Sorry for the back and forth. The bors requirements were not right.
Could you review this again @therealprof?

**Review by therealprof — APPROVED** [review]
Sure.

bors r+

**Comment by therealprof** [comment]
Just for reference: I'm not super keen on the idea of making formatting checks mandatory. We had problems in the past when formatting rules changed (similar to clippy rules) and we should actually run CI on a schedule and not just on PRs (which should be fine since they should be up-to-date re formatting).

Here's to hope that Rust is not going to make a lot of tweaks to the formatting to not get back at us. 😅 Let's see how it goes.

**Comment by eldruin** [comment]
True. clippy bit me all over the place with [a rule I believe is not good](https://github.com/rust-lang/rust-clippy/issues/6455) and I am still not even done updating all my drivers to disregard it. fmt has been quite stable so far, but yeah, good point.

**Pull request merged**
