### PR TITLE
u8 as default SPI Word

### PR DESCRIPTION
**Pull request by burrbull**
Part of #320

### CODE REVIEW

**Review by Sh3Rm4n — COMMENTED** [review]
I think this is a sensible default and may also be expanded to other traits, like the Serial traits?

**Review by Dirbaio — APPROVED** [review]
I like this! I can't think of any downside, and the *vast majority* of SPI uses are u8.

We should do the same for uart and other traits.

**Review by ryankurte — APPROVED** [review]
seems reasonable to me, any other opinions @rust-embedded/hal ?

**Comment by therealprof** [comment]
LGTM!

**Pull request merged**
