### PR TITLE
Update code formatting style to common

### PR DESCRIPTION
**Pull request by no111u3**
Update code formatting style to common rust format style.
It helps everyone to create pr without manual check coding style of project.

### CODE REVIEW

**Comment by thejpster** [comment]
Could you add something to the Travis file which checks the formatting? Something like `cargo fmt -- --check` should do it.

**Comment by no111u3** [comment]
> Could you add something to the Travis file which checks the formatting? Something like `cargo fmt -- --check` should do it.

@therealprof I update PR with adding checks the formatting on CI

**Comment by thejpster** [comment]
Thanks @no111u3

**Pull request merged**
