### PR TITLE
Prepare e-h 1.0.0-alpha.9 release

### PR DESCRIPTION
**Pull request by eldruin**

### CODE REVIEW

**Review by Dirbaio — DISMISSED** [review]
bors r+

**Review by Dirbaio — APPROVED** [review]
Rebased.

bors r+

**Comment by Dirbaio** [comment]
@eldruin I went ahead and did the release. Hope haven't missed anything: `cargo publish`, created the git tag, and created the release on github with the release notes. Is that all? :D

**Comment by eldruin** [comment]
That's all, thanks!

**Pull request merged**
