### PR TITLE
Some minor improvements

### PR DESCRIPTION
**Pull request by eldruin**
- Update codeowners
- Remove unnecessary imports
- Replace `into_iter()` with `iter()` when used on reference
- Deny warnings on cargo check and cargo test on CI (but allow them on clippy since that is a fast-moving target)

### CODE REVIEW

**Comment by eldruin** [comment]
This needs to be rebased again after #274 is merged

**Comment by eldruin** [comment]
Alright, rebased. This should be good to go now.

**Comment by burrbull** [comment]
https://doc.rust-lang.org/std/primitive.str.html#method.bytes

**Comment by eldruin** [comment]
Thanks @burrbull! That simplified the code a bit further.

**Review by ryankurte — APPROVED** [review]
:+1:

**Pull request merged**
