### PR TITLE
Update dev dependencies to actual version

### PR DESCRIPTION
**Pull request by no111u3**
I clean update developing dependencies to buildable state.

### CODE REVIEW

**Comment by therealprof** [comment]
Actually `stm32f30x` is really old and not actively maintained anymore. This should probably use `stm32f3` instead.

**Comment by no111u3** [comment]
@therealprof, I think yes. I update it in next commit

**Comment by therealprof** [comment]
Thanks. Can you squash the commits please?

**Comment by no111u3** [comment]
I did it.

**Pull request merged**
