### PR TITLE
impl Write for serial::Write

### PR DESCRIPTION
**Pull request by thenewwazoo**
Shamelessly pilfered from [@therealprof's code](https://github.com/therealprof/stm32f042-hal/blob/master/src/serial.rs). Still needs Changelog entry, but I thought this was a good idea after a discussion on IRC.

### CODE REVIEW

**Comment by thenewwazoo** [comment]
Per an IRC comment, if this is fully generic, do we need the featurengate at all?

**Comment by therealprof** [comment]
I think that was my comment. ;) Just to clarify, I think no.

@thenewwazoo Doesn't this require to pull in the `Write` trait to work?

**Comment by thenewwazoo** [comment]
That's... a good question. I was under the (mistaken?) impression that `core::fmt::Write` was in `core::prelude`.

**Comment by thenewwazoo** [comment]
Looks like this build was a spurious failure - any chance it could get merged? I'm not sure how to fix the build failure (or if it even should be fixed?)

**Comment by therealprof** [comment]
bors retry

**Comment by Disasm** [comment]
Blocked on https://github.com/rust-embedded/embedded-hal/pull/125

**Comment by mathk** [comment]
@thenewwazoo does it worth doing a rebase and see if that solve the bors issue ?

**Comment by Disasm** [comment]
bors r=ryankurte

**Comment by Disasm** [comment]
bors r=ryankurte

**Pull request merged**
