### PR TITLE
Fix Travis build

### PR DESCRIPTION
**Pull request by hannobraun**
Please ignore. I just need this pull request to figure out what's wrong with Travis.

### CODE REVIEW

**Comment by hannobraun** [comment]
This should be good to go.

@rust-embedded/hal Anyone, please review, or if not, just tell Bors to merge it. The least this will do un-break all pull request builds, which means we can finally merge pull requests again. If it breaks the automatic documentation updates, we can deal with that later.

**Comment by jamesmunns** [comment]
(oops, I have no power here :) )

**Comment by hannobraun** [comment]
Thanks everyone!

**Pull request merged**
